name: event_planning_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  fluttertoast: ^8.2.10
  introduction_screen: ^3.1.14  
  toggle_switch: ^2.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  easy_localization: ^3.0.7
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/translations/
